---
title: "Demo Code"
---

The RPCRA book has a distinctive **reproducibility** theme: most figures and tables in most chapters are reproducible using R scripts provided in the `PCRA` R package. These scripts allow students and instructors to replicate book results and experiment with different portfolio strategies, time periods, stock groups, and optimization parameters.

# Chapter Demo Scripts

Download any script directly. Each script reproduces all figures and tables for its chapter.

| Chapter    | Topic | Download Link|
|------------|-------|--------------|
| Chapter 1  | Introduction to Portfolio Management | [Download R script](demos/Ch1_Introduction_Demo.R){target="_blank"} |
| Chapter 2  | Foundations | [Download R script](demos/Ch2_Foundations_Demo.R){target="_blank"} |
| Chapter 3  | Modeling Asset Returns | [Download R script](demos/Ch3_ModelingAssetReturns_Demo.R){target="_blank"} |
| Chapter 4  | Covariance Matrices | [Download R script](demos/Ch4_CovarianceMatrices_Demo.R){target="_blank"} |
| Chapter 5  | Portfolio Constraints and Penalties | [Download R script](demos/Ch5_PortfolioConstraintsAndPenalties_Demo.R){target="_blank"} |
| Chapter 6  | Time Series Models | [Download R script](demos/Ch6_TimeSeriesModels_Demo.R){target="_blank"} |
| Chapter 10  | Performance Analysis | [Download R script](demos/Ch10_PerformanceAnalysis_Demo.R){target="_blank"} |
| Chapter 11  | Expected Returns | [Download R script](demos/Ch11_ExpectedReturns_Demo.R){target="_blank"} |
| Chapter 12  | Fixed Income Portfolio Management | [Download R script](demos/Ch12_FixedIncomePortfolioManagement_Demo.R){target="_blank"} |
| Chapter 15  | Influence Functions and Standard Errors | [Download R script](demos/Ch15_IFsandStandardErrors_Demo.R){target="_blank"} |

::: {.callout-warning appearance="minimal"}
Some scripts take several minutes to run in full. It usually proves more effective to run the initialization code and then run the code for selected Figures and Tables as needed.
:::

{{< include _copyright.qmd >}}
